<?xml version="1.0" encoding="iso-8859-1" ?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

<xsl:output method="text" omit-xml-declaration="yes" indent="no" encoding="iso-8859-1" />

<!--             -->
<!-- entry point -->
<!--             -->

<xsl:template match="/dr">
/* This file is generated by applying the dr.xsl stylesheet to the dr.xml
 * description file. DO NOT EDIT !!! */

#include "config.h"

#include &lt;stdio.h&gt;

/* the libdvbpsi distribution defines DVBPSI_DIST */
#ifdef DVBPSI_DIST
#include "../src/dvbpsi.h"
#include "../src/descriptor.h"
#include "../src/descriptors/dr.h"
#else
#include &lt;dvbpsi/dvbpsi.h&gt;
#include &lt;dvbpsi/descriptor.h&gt;
#include &lt;dvbpsi/dr.h&gt;
#endif

#include "test_dr.h"

  <xsl:apply-templates mode="code" />

/* main function */
int main()
{
  int i_err = 0;
  <xsl:apply-templates mode="main" />

  return i_err;
}

</xsl:template>

<xsl:template match="text()" priority="-1"/>

<!--                -->
<!-- code templates -->
<!--                -->

<xsl:template match="descriptor" mode="code">
/* <xsl:value-of select="@name" /> */
int main_<xsl:value-of select="@sname" />()
{
  BOZO_VARS(<xsl:value-of select="@sname" />);
  BOZO_START(<xsl:value-of select="@name" />);

  /* BEGIN start */<xsl:apply-templates mode="begin" />
  /* BEGIN end */

    BOZO_DOJOB(<xsl:value-of select="@fname" />);

    /* CHECK start */<xsl:apply-templates mode="check" />
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */<xsl:apply-templates mode="end" >
    <xsl:sort select="position()" data-type="number" order="descending" />
  </xsl:apply-templates>
  /* END end */

  BOZO_END(<xsl:value-of select="@name" />);

  return i_err;
}
</xsl:template>

<xsl:template match="text()" mode="code" priority="-1"/>

<!--                 -->
<!-- begin templates -->
<!--                 -->

<xsl:template match="integer" mode="begin">
  BOZO_begin_integer(<xsl:value-of select="@name" />, <xsl:value-of select="@bitcount" />)</xsl:template>

<xsl:template match="boolean" mode="begin">
  BOZO_begin_boolean(<xsl:value-of select="@name" />)</xsl:template>

<xsl:template match="insert" mode="begin">
  <xsl:value-of select="begin" />
</xsl:template>

<xsl:template match="text()" mode="begin" priority="-1"/>

<!--                 -->
<!-- check templates -->
<!--                 -->

<xsl:template match="integer" mode="check">
    BOZO_check_integer<xsl:if test="@bitcount='32' or @bitcount='64'" ><xsl:value-of select="@bitcount" /></xsl:if>(<xsl:value-of select="@name" />, <xsl:value-of select="@bitcount" />)</xsl:template>

<xsl:template match="boolean" mode="check">
    BOZO_check_boolean(<xsl:value-of select="@name" />)</xsl:template>

<xsl:template match="insert" mode="check">
  <xsl:value-of select="check" />
</xsl:template>

<xsl:template match="text()" mode="check" priority="-1"/>

<!--               -->
<!-- end templates -->
<!--               -->

<xsl:template match="integer" mode="end">
  BOZO_end_integer<xsl:if test="@bitcount='32' or @bitcount='64'" ><xsl:value-of select="@bitcount" /></xsl:if>(<xsl:value-of select="@name" />, <xsl:value-of select="@bitcount" />)</xsl:template>

<xsl:template match="boolean" mode="end">
  BOZO_end_boolean(<xsl:value-of select="@name" />)</xsl:template>

<xsl:template match="insert" mode="end">
  <xsl:value-of select="end" />
</xsl:template>

<xsl:template match="text()" mode="end" priority="-1"/>

<!--                -->
<!-- main templates -->
<!--                -->

<xsl:template match="descriptor" mode="main">
  i_err |= main_<xsl:value-of select="@sname" />();</xsl:template>

<xsl:template match="text()" mode="main" priority="-1"/>

</xsl:stylesheet>
