
/* This file is generated by applying the dr.xsl stylesheet to the dr.xml
 * description file. DO NOT EDIT !!! */

#include "config.h"

#include <stdio.h>

/* the libdvbpsi distribution defines DVBPSI_DIST */
#ifdef DVBPSI_DIST
#include "../src/dvbpsi.h"
#include "../src/descriptor.h"
#include "../src/descriptors/dr.h"
#else
#include <dvbpsi/dvbpsi.h>
#include <dvbpsi/descriptor.h>
#include <dvbpsi/dr.h>
#endif

#include "test_dr.h"

  
/* video stream */
int main_vstream()
{
  BOZO_VARS(vstream);
  BOZO_START(video stream);

  /* BEGIN start */
  BOZO_begin_boolean(b_multiple_frame_rate)
  BOZO_begin_integer(i_frame_rate_code, 4)
  BOZO_begin_boolean(b_mpeg2)
  BOZO_begin_boolean(b_constrained_parameter)
  BOZO_begin_boolean(b_still_picture)
  BOZO_begin_integer(i_profile_level_indication, 8)
  BOZO_begin_integer(i_chroma_format, 2)
  BOZO_begin_boolean(b_frame_rate_extension)
  /* BEGIN end */

    BOZO_DOJOB(VStream);

    /* CHECK start */
    BOZO_check_boolean(b_multiple_frame_rate)
    BOZO_check_integer(i_frame_rate_code, 4)
    BOZO_check_boolean(b_mpeg2)
    BOZO_check_boolean(b_constrained_parameter)
    BOZO_check_boolean(b_still_picture)
    if(s_decoded.b_mpeg2)
    {
    BOZO_check_integer(i_profile_level_indication, 8)
    BOZO_check_integer(i_chroma_format, 2)
    BOZO_check_boolean(b_frame_rate_extension)
    }
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_boolean(b_frame_rate_extension)
  BOZO_end_integer(i_chroma_format, 2)
  BOZO_end_integer(i_profile_level_indication, 8)
  BOZO_end_boolean(b_still_picture)
  BOZO_end_boolean(b_constrained_parameter)
  BOZO_end_boolean(b_mpeg2)
  BOZO_end_integer(i_frame_rate_code, 4)
  BOZO_end_boolean(b_multiple_frame_rate)
  /* END end */

  BOZO_END(video stream);

  return i_err;
}

/* audio stream */
int main_astream()
{
  BOZO_VARS(astream);
  BOZO_START(audio stream);

  /* BEGIN start */
  BOZO_begin_boolean(b_free_format)
  BOZO_begin_integer(i_id, 1)
  BOZO_begin_integer(i_layer, 2)
  /* BEGIN end */

    BOZO_DOJOB(AStream);

    /* CHECK start */
    BOZO_check_boolean(b_free_format)
    BOZO_check_integer(i_id, 1)
    BOZO_check_integer(i_layer, 2)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer(i_layer, 2)
  BOZO_end_integer(i_id, 1)
  BOZO_end_boolean(b_free_format)
  /* END end */

  BOZO_END(audio stream);

  return i_err;
}

/* hierarchy */
int main_hierarchy()
{
  BOZO_VARS(hierarchy);
  BOZO_START(hierarchy);

  /* BEGIN start */
  BOZO_begin_integer(i_h_type, 4)
  BOZO_begin_integer(i_h_layer_index, 6)
  BOZO_begin_integer(i_h_embedded_layer, 6)
  BOZO_begin_integer(i_h_priority, 6)
  /* BEGIN end */

    BOZO_DOJOB(Hierarchy);

    /* CHECK start */
    BOZO_check_integer(i_h_type, 4)
    BOZO_check_integer(i_h_layer_index, 6)
    BOZO_check_integer(i_h_embedded_layer, 6)
    BOZO_check_integer(i_h_priority, 6)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer(i_h_priority, 6)
  BOZO_end_integer(i_h_embedded_layer, 6)
  BOZO_end_integer(i_h_layer_index, 6)
  BOZO_end_integer(i_h_type, 4)
  /* END end */

  BOZO_END(hierarchy);

  return i_err;
}

/* registration */
int main_registration()
{
  BOZO_VARS(registration);
  BOZO_START(registration);

  /* BEGIN start */
  s_decoded.i_additional_length = 0;
  BOZO_begin_integer(i_format_identifier, 32)
  /* BEGIN end */

    BOZO_DOJOB(Registration);

    /* CHECK start */
    BOZO_check_integer32(i_format_identifier, 32)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer32(i_format_identifier, 32)
  /* END end */

  BOZO_END(registration);

  return i_err;
}

/* data stream alignment */
int main_ds_alignment()
{
  BOZO_VARS(ds_alignment);
  BOZO_START(data stream alignment);

  /* BEGIN start */
  BOZO_begin_integer(i_alignment_type, 8)
  /* BEGIN end */

    BOZO_DOJOB(DSAlignment);

    /* CHECK start */
    BOZO_check_integer(i_alignment_type, 8)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer(i_alignment_type, 8)
  /* END end */

  BOZO_END(data stream alignment);

  return i_err;
}

/* target background grid */
int main_target_bg_grid()
{
  BOZO_VARS(target_bg_grid);
  BOZO_START(target background grid);

  /* BEGIN start */
  BOZO_begin_integer(i_horizontal_size, 14)
  BOZO_begin_integer(i_vertical_size, 14)
  BOZO_begin_integer(i_pel_aspect_ratio, 4)
  /* BEGIN end */

    BOZO_DOJOB(TargetBgGrid);

    /* CHECK start */
    BOZO_check_integer(i_horizontal_size, 14)
    BOZO_check_integer(i_vertical_size, 14)
    BOZO_check_integer(i_pel_aspect_ratio, 4)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer(i_pel_aspect_ratio, 4)
  BOZO_end_integer(i_vertical_size, 14)
  BOZO_end_integer(i_horizontal_size, 14)
  /* END end */

  BOZO_END(target background grid);

  return i_err;
}

/* video window */
int main_vwindow()
{
  BOZO_VARS(vwindow);
  BOZO_START(video window);

  /* BEGIN start */
  BOZO_begin_integer(i_horizontal_offset, 14)
  BOZO_begin_integer(i_vertical_offset, 14)
  BOZO_begin_integer(i_window_priority, 4)
  /* BEGIN end */

    BOZO_DOJOB(VWindow);

    /* CHECK start */
    BOZO_check_integer(i_horizontal_offset, 14)
    BOZO_check_integer(i_vertical_offset, 14)
    BOZO_check_integer(i_window_priority, 4)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer(i_window_priority, 4)
  BOZO_end_integer(i_vertical_offset, 14)
  BOZO_end_integer(i_horizontal_offset, 14)
  /* END end */

  BOZO_END(video window);

  return i_err;
}

/* conditional access */
int main_ca()
{
  BOZO_VARS(ca);
  BOZO_START(conditional access);

  /* BEGIN start */
  s_decoded.i_private_length = 0;
  BOZO_begin_integer(i_ca_system_id, 16)
  BOZO_begin_integer(i_ca_pid, 13)
  /* BEGIN end */

    BOZO_DOJOB(CA);

    /* CHECK start */
    BOZO_check_integer(i_ca_system_id, 16)
    BOZO_check_integer(i_ca_pid, 13)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer(i_ca_pid, 13)
  BOZO_end_integer(i_ca_system_id, 16)
  /* END end */

  BOZO_END(conditional access);

  return i_err;
}

/* ISO 639 language */
int main_iso639()
{
  BOZO_VARS(iso639);
  BOZO_START(ISO 639 language);

  /* BEGIN start */
  s_decoded.i_code_count = 0;
  BOZO_begin_integer(i_audio_type, 8)
  /* BEGIN end */

    BOZO_DOJOB(ISO639);

    /* CHECK start */
    BOZO_check_integer(i_audio_type, 8)
    /* CHECK end */

    BOZO_CLEAN();

  /* END start */
  BOZO_end_integer(i_audio_type, 8)
  /* END end */

  BOZO_END(ISO 639 language);

  return i_err;
}


/* main function */
int main()
{
  int i_err = 0;
  
  i_err |= main_vstream();
  i_err |= main_astream();
  i_err |= main_hierarchy();
  i_err |= main_registration();
  i_err |= main_ds_alignment();
  i_err |= main_target_bg_grid();
  i_err |= main_vwindow();
  i_err |= main_ca();
  i_err |= main_iso639();

  return i_err;
}

