#! /bin/sh

##  bootstrap file for libdvbpsi -- Sam Hocevar <sam@zoy.org>
##  $Id: bootstrap,v 1.5 2003/11/06 10:13:40 sam Exp $

set -x
set -e

# Get a sane environment, just in case
LANG=C
export LANG
CYGWIN=binmode
export CYGWIN

# Check for automake
amvers="no"
if automake-1.7 --version >/dev/null 2>&1; then
  amvers="-1.7"
elif automake-1.6 --version >/dev/null 2>&1; then
  amvers="-1.6"
elif automake-1.5 --version >/dev/null 2>&1; then
  amvers="-1.5"
elif automake --version > /dev/null 2>&1; then
  amvers="`automake --version | sed -e '1s/[^0-9]*//' -e q`"
  if expr "$amvers" "<" "1.5" > /dev/null 2>&1; then
    amvers="no"
  else
    amvers=""
  fi
fi

if test "$amvers" = "no"; then
  set +x
  echo "$0: you need automake version 1.5 or later"
  exit 1
fi

# Check for libtool
libtoolize="no"
if libtoolize --version >/dev/null 2>&1; then
  libtoolize="libtoolize"
elif glibtoolize --version >/dev/null 2>&1; then
  libtoolize="glibtoolize"
fi

if test "$libtoolize" = "no"; then
  set +x
  echo "$0: you need libtool"
  exit 1
fi

# Remove old cruft
rm -f aclocal.m4 configure config.guess config.log config.sub config.cache config.h.in config.h compile ltmain.sh libtool ltconfig missing mkinstalldirs depcomp install-sh
rm -Rf autom4te.cache
(cd autotools && rm -f config.guess config.sub missing mkinstalldirs compile ltmain.sh depcomp install-sh)

aclocal${amvers}
${libtoolize} --copy --force

if test -f "ltmain.sh"; then
  echo "$0: working around a minor libtool issue"
  mv ltmain.sh autotools/
fi

autoconf
autoheader
automake${amvers} --add-missing --copy

